[package]
name = "snow"
description = "A pure-rust implementation of the Noise Protocol Framework"
homepage = "https://snow.rs"
documentation = "https://snow.rs/doc/snow"
repository = "https://github.com/mcginty/snow"
version = "0.1.12"
authors = ["Jake McGinty <me@jake.su>", "trevp"]
license = "Unlicense"
categories = ["cryptography"]
readme = "README.md"
keywords = ["noise", "protocol", "crypto"]

[features]
default = ["ring-accelerated"]
nightly = ["blake2-rfc/simd_opt", "chacha20-poly1305-aead/simd_opt", "x25519-dalek/nightly"]
hacl-resolver = ["hacl-star"]
hacl-accelerated = ["hacl-resolver"]
ring-resolver = ["ring"]
ring-accelerated = ["ring", "ring-resolver"]
vector-tests = []

[[bench]]
name = "benches"
harness = false

[badges]
travis-ci = { repository = "mcginty/snow", branch = "master" }
appveyor = { repository = "mcginty/snow", branch = "master", service = "github" }

[dependencies]
arrayvec = "^0.4"
arrayref = "^0.3"
failure = "^0.1"
rust-crypto = { git = "https://github.com/mcginty/rust-crypto" }
byteorder = "^1.2"
rand = "0.5.0-pre.2"
static_slice = "0.0.3"
blake2-rfc = "^0.2"
chacha20-poly1305-aead = "^0.1"
x25519-dalek = { version = "^0.2", default-features = false, features = ["std", "u64_backend"] }
hacl-star = { version = "=0.0.11", optional = true }
ring = { version = "0.13.0-alpha", optional = true }

[dev-dependencies]
clap = "^2.0"
criterion = "0.2"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
hex = "^0.2"
lazy_static = "^1.0"

[build-dependencies]
rustc_version = "^0.2"

[package.metadata.docs.rs]
features = [ "ring-resolver", "hacl-resolver" ]
all-features = false
no-default-features = false

